resource:
  nextResetTime: '2024-02-24T06:00:00.024183424'
world_nether:
  nextResetTime: '2024-03-01T09:00:00.557973853'
world_the_end:
  nextResetTime: '2024-03-10T04:00:00.951736933'
worlds:
  resource:
    displayName: "Resource World"
    color: "&a"  # Green
  world_nether:
    displayName: "Nether World"
    color: "&c"  # Red
  world_the_end:
    displayName: "End World"
    color: "&5"  # Dark Purple