name: ABMCWorldNotify
main: server.alanbecker.net.Notify
author: MasterGabeMOD
version: 1.1
api-version: 1.19
commands:
  worldnotify:
    description: Reload the configuration.
    usage: /worldnotify reload
    permission: worldnotify.reload
permissions:
  worldnotify.reload:
    description: Allows reloading configuration.
    default: op
